/* Generated by Amaranth Yosys 0.40 (PyPI ver 0.40.0.0.post95, git sha1 a1bb0255d) */

(* top =  1  *)
(* generator = "Amaranth" *)
module top(bit_phase_0, bit_phase_1, input_fock_state_str);
  reg \$auto$verilog_backend.cc:2352:dump_module$1  = 0;
  (* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:88" *)
  output [4:0] bit_phase_0;
  reg [4:0] bit_phase_0;
  (* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:88" *)
  output [4:0] bit_phase_1;
  reg [4:0] bit_phase_1;
  (* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:84" *)
  input [2:0] input_fock_state_str;
  wire [2:0] input_fock_state_str;
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:114" *)
    casez (input_fock_state_str)
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:117" */
      3'h4:
          bit_phase_0 = 5'h00;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:117" */
      3'h1:
          bit_phase_0 = 5'h00;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:117" */
      3'h2:
          bit_phase_0 = 5'h1f;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:126" */
      default:
          bit_phase_0 = 5'h00;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:114" *)
    casez (input_fock_state_str)
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:117" */
      3'h4:
          bit_phase_1 = 5'h00;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:117" */
      3'h1:
          bit_phase_1 = 5'h1f;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:117" */
      3'h2:
          bit_phase_1 = 5'h00;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:126" */
      default:
          bit_phase_1 = 5'h00;
    endcase
  end
endmodule
