#!/bin/bash
# Makefile
SIM ?= icarus
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES += C:\Users\dario\Documents\phd\piel\docs\examples\designs\simple_design\simple_design\src\.ipynb_checkpoints
VERILOG_SOURCES += C:\Users\dario\Documents\phd\piel\docs\examples\designs\simple_design\simple_design\src\adder.sv
VERILOG_SOURCES += C:\Users\dario\Documents\phd\piel\docs\examples\designs\simple_design\simple_design\src\adder.vhdl
TOPLEVEL := adder
MODULE := test_adder
include $(shell cocotb-config --makefiles)/Makefile.sim
