/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

(* top =  1  *)
(* generator = "Amaranth" *)
module top(phase_map_out, clk, rst, detector_in);
  reg \$auto$verilog_backend.cc:2334:dump_module$1  = 0;
  (* src = "/home/daquintero/.pyenv/versions/3.10.13/envs/piel_0_57/lib/python3.10/site-packages/amaranth/hdl/ir.py:508" *)
  input clk;
  wire clk;
  (* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:139" *)
  input [1:0] detector_in;
  wire [1:0] detector_in;
  (* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:160" *)
  reg [1:0] next_state = 2'h0;
  (* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:160" *)
  reg [1:0] \next_state$next ;
  (* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:141" *)
  output [1:0] phase_map_out;
  reg [1:0] phase_map_out = 2'h0;
  (* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:141" *)
  reg [1:0] \phase_map_out$next ;
  (* src = "/home/daquintero/.pyenv/versions/3.10.13/envs/piel_0_57/lib/python3.10/site-packages/amaranth/hdl/ir.py:508" *)
  input rst;
  wire rst;
  (* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:154" *)
  reg [1:0] state = 2'h0;
  (* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:154" *)
  reg [1:0] \state$next ;
  always @(posedge clk)
    state <= \state$next ;
  always @(posedge clk)
    next_state <= \next_state$next ;
  always @(posedge clk)
    phase_map_out <= \phase_map_out$next ;
  always @* begin
    if (\$auto$verilog_backend.cc:2334:dump_module$1 ) begin end
    \state$next  = next_state;
    (* src = "/home/daquintero/.pyenv/versions/3.10.13/envs/piel_0_57/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:503" *)
    if (rst) begin
      \state$next  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2334:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:165" *)
    casez (detector_in)
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:168" */
      2'h0:
          \next_state$next  = 2'h0;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:168" */
      2'h1:
          \next_state$next  = 2'h1;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:168" */
      2'h2:
          \next_state$next  = 2'h2;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:168" */
      2'h3:
          \next_state$next  = 2'h3;
    endcase
    (* src = "/home/daquintero/.pyenv/versions/3.10.13/envs/piel_0_57/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:503" *)
    if (rst) begin
      \next_state$next  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2334:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:165" *)
    casez (detector_in)
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:168" */
      2'h0:
          \phase_map_out$next  = 2'h0;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:168" */
      2'h1:
          \phase_map_out$next  = 2'h2;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:168" */
      2'h2:
          \phase_map_out$next  = 2'h3;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:168" */
      2'h3:
          \phase_map_out$next  = 2'h3;
    endcase
    (* src = "/home/daquintero/.pyenv/versions/3.10.13/envs/piel_0_57/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:503" *)
    if (rst) begin
      \phase_map_out$next  = 2'h0;
    end
  end
endmodule
