/* Generated by Amaranth Yosys 0.40 (PyPI ver 0.40.0.0.post99, git sha1 a1bb0255d) */

(* top =  1  *)
(* generator = "Amaranth" *)
module top(phase_map_out, clk, rst, detector_in);
  reg \$auto$verilog_backend.cc:2352:dump_module$1  = 0;
  (* src = "/home/daquintero/phd/piel/.venv/lib/python3.10/site-packages/amaranth/hdl/ir.py:508" *)
  input clk;
  wire clk;
  (* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:139" *)
  input [1:0] detector_in;
  wire [1:0] detector_in;
  (* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:164" *)
  reg [1:0] next_state = 2'h0;
  (* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:164" *)
  reg [1:0] \next_state$next ;
  (* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:143" *)
  output [1:0] phase_map_out;
  reg [1:0] phase_map_out = 2'h0;
  (* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:143" *)
  reg [1:0] \phase_map_out$next ;
  (* src = "/home/daquintero/phd/piel/.venv/lib/python3.10/site-packages/amaranth/hdl/ir.py:508" *)
  input rst;
  wire rst;
  (* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:156" *)
  reg [1:0] state = 2'h0;
  (* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:156" *)
  reg [1:0] \state$next ;
  always @(posedge clk)
    state <= \state$next ;
  always @(posedge clk)
    next_state <= \next_state$next ;
  always @(posedge clk)
    phase_map_out <= \phase_map_out$next ;
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \state$next  = next_state;
    (* src = "/home/daquintero/phd/piel/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:503" *)
    if (rst) begin
      \state$next  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:169" *)
    casez (detector_in)
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:172" */
      2'h0:
          \next_state$next  = 2'h0;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:172" */
      2'h1:
          \next_state$next  = 2'h1;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:172" */
      2'h2:
          \next_state$next  = 2'h2;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:172" */
      2'h3:
          \next_state$next  = 2'h3;
    endcase
    (* src = "/home/daquintero/phd/piel/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:503" *)
    if (rst) begin
      \next_state$next  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:169" *)
    casez (detector_in)
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:172" */
      2'h0:
          \phase_map_out$next  = 2'h0;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:172" */
      2'h1:
          \phase_map_out$next  = 2'h2;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:172" */
      2'h2:
          \phase_map_out$next  = 2'h3;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:172" */
      2'h3:
          \phase_map_out$next  = 2'h3;
    endcase
    (* src = "/home/daquintero/phd/piel/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:503" *)
    if (rst) begin
      \phase_map_out$next  = 2'h0;
    end
  end
endmodule
