/* Generated by Yosys 0.30+48 (git sha1 14d50a176d5, clang++ 11.1.0 -fPIC -Os) */

(* \amaranth.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module top(phase_map_out, detector_in);
  reg \$auto$verilog_backend.cc:2097:dump_module$1  = 0;
  (* src = "/home/daquintero/piel/piel/tools/amaranth/construct.py:43" *)
  input [1:0] detector_in;
  wire [1:0] detector_in;
  (* src = "/home/daquintero/piel/piel/tools/amaranth/construct.py:43" *)
  output [1:0] phase_map_out;
  reg [1:0] phase_map_out;
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/daquintero/piel/piel/tools/amaranth/construct.py:57" *)
    casez (detector_in)
      /* src = "/home/daquintero/piel/piel/tools/amaranth/construct.py:60" */
      2'h0:
          phase_map_out = 2'h0;
      /* src = "/home/daquintero/piel/piel/tools/amaranth/construct.py:60" */
      2'h1:
          phase_map_out = 2'h2;
      /* src = "/home/daquintero/piel/piel/tools/amaranth/construct.py:60" */
      2'h2:
          phase_map_out = 2'h3;
      /* src = "/home/daquintero/piel/piel/tools/amaranth/construct.py:60" */
      2'h3:
          phase_map_out = 2'h3;
    endcase
  end
endmodule
