/* Generated by Amaranth Yosys 0.25 (PyPI ver 0.25.0.0.post74, git sha1 e02b7f64b) */

(* \amaranth.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module top(\$signal$1 , \$signal );
  reg \$auto$verilog_backend.cc:2083:dump_module$1  = 0;
  (* src = "c:\\users\\dario\\documents\\phd\\piel\\piel\\tools\\amaranth\\construct.py:51" *)
  wire \$2 ;
  (* src = "c:\\users\\dario\\documents\\phd\\piel\\piel\\tools\\amaranth\\construct.py:51" *)
  wire \$4 ;
  (* src = "c:\\users\\dario\\documents\\phd\\piel\\piel\\tools\\amaranth\\construct.py:51" *)
  wire \$6 ;
  (* src = "c:\\users\\dario\\documents\\phd\\piel\\piel\\tools\\amaranth\\construct.py:51" *)
  wire \$8 ;
  (* src = "c:\\users\\dario\\documents\\phd\\piel\\piel\\tools\\amaranth\\construct.py:41" *)
  input [1:0] \$signal ;
  wire [1:0] \$signal ;
  (* src = "c:\\users\\dario\\documents\\phd\\piel\\piel\\tools\\amaranth\\construct.py:41" *)
  output [1:0] \$signal$1 ;
  reg [1:0] \$signal$1 ;
  assign \$2  = ! (* src = "c:\\users\\dario\\documents\\phd\\piel\\piel\\tools\\amaranth\\construct.py:51" *) \$signal ;
  assign \$4  = \$signal  == (* src = "c:\\users\\dario\\documents\\phd\\piel\\piel\\tools\\amaranth\\construct.py:51" *) 1'h1;
  assign \$6  = \$signal  == (* src = "c:\\users\\dario\\documents\\phd\\piel\\piel\\tools\\amaranth\\construct.py:51" *) 2'h2;
  assign \$8  = \$signal  == (* src = "c:\\users\\dario\\documents\\phd\\piel\\piel\\tools\\amaranth\\construct.py:51" *) 2'h3;
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$1 ) begin end
    \$signal$1  = 2'h0;
    (* src = "c:\\users\\dario\\documents\\phd\\piel\\piel\\tools\\amaranth\\construct.py:50" *)
    casez (\$2 )
      /* src = "c:\\users\\dario\\documents\\phd\\piel\\piel\\tools\\amaranth\\construct.py:50" */
      1'h1:
          \$signal$1  = 2'h0;
    endcase
    (* src = "c:\\users\\dario\\documents\\phd\\piel\\piel\\tools\\amaranth\\construct.py:50" *)
    casez (\$4 )
      /* src = "c:\\users\\dario\\documents\\phd\\piel\\piel\\tools\\amaranth\\construct.py:50" */
      1'h1:
          \$signal$1  = 2'h2;
    endcase
    (* src = "c:\\users\\dario\\documents\\phd\\piel\\piel\\tools\\amaranth\\construct.py:50" *)
    casez (\$6 )
      /* src = "c:\\users\\dario\\documents\\phd\\piel\\piel\\tools\\amaranth\\construct.py:50" */
      1'h1:
          \$signal$1  = 2'h3;
    endcase
    (* src = "c:\\users\\dario\\documents\\phd\\piel\\piel\\tools\\amaranth\\construct.py:50" *)
    casez (\$8 )
      /* src = "c:\\users\\dario\\documents\\phd\\piel\\piel\\tools\\amaranth\\construct.py:50" */
      1'h1:
          \$signal$1  = 2'h3;
    endcase
  end
endmodule
