/* Generated by Amaranth Yosys 0.40 (PyPI ver 0.40.0.0.post99, git sha1 a1bb0255d) */

(* top =  1  *)
(* generator = "Amaranth" *)
module top(\output , \input );
  reg \$auto$verilog_backend.cc:2352:dump_module$1  = 0;
  (* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:82" *)
  input [3:0] \input ;
  wire [3:0] \input ;
  (* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:86" *)
  output [3:0] \output ;
  reg [3:0] \output ;
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:112" *)
    casez (\input )
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:115" */
      4'h0:
          \output  = 4'h5;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:115" */
      4'h1:
          \output  = 4'hc;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:115" */
      4'h2:
          \output  = 4'h5;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:115" */
      4'h3:
          \output  = 4'h6;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:115" */
      4'h4:
          \output  = 4'h2;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:115" */
      4'h5:
          \output  = 4'hd;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:115" */
      4'h6:
          \output  = 4'h6;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:115" */
      4'h7:
          \output  = 4'h3;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:115" */
      4'h8:
          \output  = 4'h9;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:115" */
      4'h9:
          \output  = 4'he;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:115" */
      4'ha:
          \output  = 4'h4;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:115" */
      4'hb:
          \output  = 4'h8;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:115" */
      4'hc:
          \output  = 4'h1;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:115" */
      4'hd:
          \output  = 4'hb;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:115" */
      4'he:
          \output  = 4'hf;
      /* src = "/home/daquintero/phd/piel/piel/tools/amaranth/construct.py:115" */
      4'hf:
          \output  = 4'ha;
    endcase
  end
endmodule
