name: nix-flake-test
on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches:
      - develop
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Nix
      - name: Install and Build Nix with script
        run: source scripts/install_piel_nix.sh

      # Step 6: Run flake checks/tests
      - name: Run Flake Checks
        run: nix flake check

      # Step 6: Run piel tests
      - name: Run piel tests
        run: nix develop . --command python -m pytest tests/
