/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

(* top =  1  *)
(* generator = "Amaranth" *)
module top(\output , \input );
  reg \$auto$verilog_backend.cc:2334:dump_module$1  = 0;
  (* src = "/nix/store/xb6l9p24ndhj4r0lqcch4gi492xpgn1c-python3.11-piel-0.1.0/lib/python3.11/site-packages/piel/tools/amaranth/construct.py:82" *)
  input [3:0] \input ;
  wire [3:0] \input ;
  (* src = "/nix/store/xb6l9p24ndhj4r0lqcch4gi492xpgn1c-python3.11-piel-0.1.0/lib/python3.11/site-packages/piel/tools/amaranth/construct.py:86" *)
  output [3:0] \output ;
  reg [3:0] \output ;
  always @* begin
    if (\$auto$verilog_backend.cc:2334:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/nix/store/xb6l9p24ndhj4r0lqcch4gi492xpgn1c-python3.11-piel-0.1.0/lib/python3.11/site-packages/piel/tools/amaranth/construct.py:112" *)
    casez (\input )
      /* src = "/nix/store/xb6l9p24ndhj4r0lqcch4gi492xpgn1c-python3.11-piel-0.1.0/lib/python3.11/site-packages/piel/tools/amaranth/construct.py:115" */
      4'h0:
          \output  = 4'h5;
      /* src = "/nix/store/xb6l9p24ndhj4r0lqcch4gi492xpgn1c-python3.11-piel-0.1.0/lib/python3.11/site-packages/piel/tools/amaranth/construct.py:115" */
      4'h1:
          \output  = 4'hc;
      /* src = "/nix/store/xb6l9p24ndhj4r0lqcch4gi492xpgn1c-python3.11-piel-0.1.0/lib/python3.11/site-packages/piel/tools/amaranth/construct.py:115" */
      4'h2:
          \output  = 4'h5;
      /* src = "/nix/store/xb6l9p24ndhj4r0lqcch4gi492xpgn1c-python3.11-piel-0.1.0/lib/python3.11/site-packages/piel/tools/amaranth/construct.py:115" */
      4'h3:
          \output  = 4'h6;
      /* src = "/nix/store/xb6l9p24ndhj4r0lqcch4gi492xpgn1c-python3.11-piel-0.1.0/lib/python3.11/site-packages/piel/tools/amaranth/construct.py:115" */
      4'h4:
          \output  = 4'h2;
      /* src = "/nix/store/xb6l9p24ndhj4r0lqcch4gi492xpgn1c-python3.11-piel-0.1.0/lib/python3.11/site-packages/piel/tools/amaranth/construct.py:115" */
      4'h5:
          \output  = 4'hd;
      /* src = "/nix/store/xb6l9p24ndhj4r0lqcch4gi492xpgn1c-python3.11-piel-0.1.0/lib/python3.11/site-packages/piel/tools/amaranth/construct.py:115" */
      4'h6:
          \output  = 4'h6;
      /* src = "/nix/store/xb6l9p24ndhj4r0lqcch4gi492xpgn1c-python3.11-piel-0.1.0/lib/python3.11/site-packages/piel/tools/amaranth/construct.py:115" */
      4'h7:
          \output  = 4'h3;
      /* src = "/nix/store/xb6l9p24ndhj4r0lqcch4gi492xpgn1c-python3.11-piel-0.1.0/lib/python3.11/site-packages/piel/tools/amaranth/construct.py:115" */
      4'h8:
          \output  = 4'h9;
      /* src = "/nix/store/xb6l9p24ndhj4r0lqcch4gi492xpgn1c-python3.11-piel-0.1.0/lib/python3.11/site-packages/piel/tools/amaranth/construct.py:115" */
      4'h9:
          \output  = 4'he;
      /* src = "/nix/store/xb6l9p24ndhj4r0lqcch4gi492xpgn1c-python3.11-piel-0.1.0/lib/python3.11/site-packages/piel/tools/amaranth/construct.py:115" */
      4'ha:
          \output  = 4'h4;
      /* src = "/nix/store/xb6l9p24ndhj4r0lqcch4gi492xpgn1c-python3.11-piel-0.1.0/lib/python3.11/site-packages/piel/tools/amaranth/construct.py:115" */
      4'hb:
          \output  = 4'h8;
      /* src = "/nix/store/xb6l9p24ndhj4r0lqcch4gi492xpgn1c-python3.11-piel-0.1.0/lib/python3.11/site-packages/piel/tools/amaranth/construct.py:115" */
      4'hc:
          \output  = 4'h1;
      /* src = "/nix/store/xb6l9p24ndhj4r0lqcch4gi492xpgn1c-python3.11-piel-0.1.0/lib/python3.11/site-packages/piel/tools/amaranth/construct.py:115" */
      4'hd:
          \output  = 4'hb;
      /* src = "/nix/store/xb6l9p24ndhj4r0lqcch4gi492xpgn1c-python3.11-piel-0.1.0/lib/python3.11/site-packages/piel/tools/amaranth/construct.py:115" */
      4'he:
          \output  = 4'hf;
      /* src = "/nix/store/xb6l9p24ndhj4r0lqcch4gi492xpgn1c-python3.11-piel-0.1.0/lib/python3.11/site-packages/piel/tools/amaranth/construct.py:115" */
      4'hf:
          \output  = 4'ha;
    endcase
  end
endmodule
